// Generated by ReScript, PLEASE EDIT WITH CARE


function shutdown(param) {
  window.ChannelIO("shutdown");
}

function showMessenger(param) {
  window.ChannelIO("showMessenger");
}

function showChannelButton(param) {
  window.ChannelIO("showChannelButton");
}

function hideChannelButton(param) {
  window.ChannelIO("hideChannelButton");
}

export {
  shutdown ,
  showMessenger ,
  showChannelButton ,
  hideChannelButton ,
}
/* No side effect */
